[package]
name = "tasks"
version = "0.4.1"
authors = ["Rasmus Kildevæld <rasmuskildevaeld@gmail.com>"]
edition = "2018"

[dependencies]
pin-project = "0.4"
futures-core = "0.3"
futures-util = "0.3"

[dev-dependencies]
futures = "0.3"