[package]
name = "tasks"
version = "0.1.0"
authors = ["Rasmus Kildevæld <rasmuskildevaeld@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-core-preview = "=0.3.0-alpha.18"
futures-util-preview = "=0.3.0-alpha.18"
futures-channel-preview = "=0.3.0-alpha.18"
pin-utils = "0.1.0-alpha.3"

[dev-dependencies]
futures-executor-preview = "=0.3.0-alpha.18"